apiVersion: ark.mckinsey.com/v1alpha1
kind: Agent
metadata:
  name: sample-{{ .Values.mcpServerName }}-agent
  labels:
    app.kubernetes.io/name: {{ .Values.mcpServerName }}
    app.kubernetes.io/component: agent
spec:
  model:
    name: default
  system: |
    You are an AI assistant that can use {{ .Values.mcpServerName }} tools to help users.
    
    Available tools from {{ .Values.mcpServerName }}:
{{- range .Values.tools }}
    - {{ .name }}: {{ .description }}
{{- end }}
    
    Use these tools when appropriate to help users with their requests.
  
  tools:
    - mcpServers:
        - name: {{ .Values.mcpServerName }}-server
{{- if .Values.toolConfigurations }}
{{- range .Values.toolConfigurations }}
    - name: {{ .name }}
      description: {{ .description }}
{{- if .parameters }}
      parameters:
{{- toYaml .parameters | nindent 8 }}
{{- end }}
{{- end }}
{{- end }}