version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: fark
    main: ./cmd/fark
    binary: fark
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - id: fark
    ids:
      - fark
    name_template: >-
      fark-cli_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
      - "^refactor:"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: McK-Internal
    name: agents-at-scale
  name_template: "Ark CLI {{.Tag}}"
  header: |
    ## Ark CLI Release {{.Tag}}
    
    This release contains the Ark CLI binary for multiple platforms.
    
    ### Installation
    
    Download the appropriate binary for your platform from the assets below.
    
    #### Linux/macOS
    ```bash
    # Download and install (replace URL with actual release URL)
    curl -L -o fark https://github.com/McK-Internal/agents-at-scale/releases/download/{{.Tag}}/fark-cli_Linux_x86_64.tar.gz
    tar -xzf fark-cli_Linux_x86_64.tar.gz
    chmod +x fark
    sudo mv fark /usr/local/bin/
    ```
    
    #### Windows
    Download the `fark-cli_Windows_x86_64.zip` file and extract the `fark.exe` binary.
    
  footer: |
    ## Checksums
    
    All checksums are available in the `checksums.txt` file.
    
    **Full Changelog**: https://github.com/McK-Internal/agents-at-scale/compare/{{.PreviousTag}}...{{.Tag}}