apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mcp-filesys.fullname" . }}-filebrowser
  labels:
    {{- include "mcp-filesys.labels" . | nindent 4 }}
    app.kubernetes.io/component: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mcp-filesys.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: filebrowser
  template:
    metadata:
      labels:
        {{- include "mcp-filesys.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: filebrowser
    spec:
      serviceAccountName: {{ .Values.filebrowser.serviceAccount.name }}
      automountServiceAccountToken: false
      containers:
        - name: filebrowser
          image: "{{ .Values.filebrowser.image.repository }}:{{ .Values.filebrowser.image.tag }}"
          imagePullPolicy: {{ .Values.filebrowser.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: FB_ROOT
              value: "/srv"
            - name: FB_DATABASE
              value: "/database/filebrowser.db"
          volumeMounts:
            - name: data
              mountPath: /srv
            - name: database
              mountPath: /database
          resources:
            {{- toYaml .Values.filebrowser.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "mcp-filesys.fullname" . }}-data
        - name: database
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}