apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-filesys.name" . }}-server
  labels:
    {{- include "mcp-filesys.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mcp-filesys.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-server