{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.serviceAccount.name }}-ark-resources
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.name }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
- apiGroups: ["ark.mckinsey.com"]
  resources: ["agents"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["ark.mckinsey.com"]
  resources: ["queries"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceAccount.name }}-ark-binding
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.name }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.serviceAccount.name }}-ark-resources
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
{{- end }}