apiVersion: ark.mckinsey.com/v1prealpha1
kind: ExecutionEngine
metadata:
  name: {{ include "executor-langchain.fullname" . }}
  labels:
    {{- include "executor-langchain.labels" . | nindent 4 }}
spec:
  type: "langchain"
  address:
    valueFrom:
      serviceRef:
        name: {{ include "executor-langchain.fullname" . }}
        {{- if .Values.executionEngine.address.serviceRef.namespace }}
        namespace: {{ .Values.executionEngine.address.serviceRef.namespace }}
        {{- end }}
        {{- if .Values.executionEngine.address.serviceRef.port }}
        port: "{{ .Values.executionEngine.address.serviceRef.port }}"
        {{- end }}
        {{- if .Values.executionEngine.address.serviceRef.path }}
        path: {{ .Values.executionEngine.address.serviceRef.path }}
        {{- end }}
  description: {{ .Values.executionEngine.description | quote }}