{{- if and .Values.requiresAuth (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "{{ .Values.mcpServerName }}.fullname" . }}
  labels:
    {{- include "{{ .Values.mcpServerName }}.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.existingSecretKey }}: {{ .Values.auth.token | b64enc }}
{{- end }}