apiVersion: v1
kind: Service
metadata:
  name: {{ include "{{ .Values.mcpServerName }}.fullname" . }}
  labels:
    {{- include "{{ .Values.mcpServerName }}.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "{{ .Values.mcpServerName }}.selectorLabels" . | nindent 4 }}