apiVersion: v1
kind: Secret
metadata:
  name: anthropic-api-key
type: Opaque
stringData:
  # Make sure to use 
  # export ANTHROPIC_API_KEY="key"
  # envsubst < samples/models/claude.yaml | kubectl apply -f -
  apiKey: ${ANTHROPIC_API_KEY}
---
apiVersion: ark.mckinsey.com/v1alpha1
kind: Model
metadata:
  name: claude
spec:
  type: openai
  model:
    value: claude-opus-4-20250514
  config:
    openai:
      baseUrl:
        value: "https://api.anthropic.com/v1/"
      apiKey:
        valueFrom:
          secretKeyRef:
            name: anthropic-api-key
            key: apiKey
