apiVersion: ark.mckinsey.com/v1alpha1
kind: Agent
metadata:
  name: azure
spec:
  prompt: You're helpful agent. Always add model name to the output.
---
apiVersion: ark.mckinsey.com/v1alpha1
kind: Agent
metadata:
  name: gemini
spec:
  prompt: You're helpful agent. Always add model name to the output.
  modelRef:
    name: gemini
---
apiVersion: ark.mckinsey.com/v1alpha1
kind: Query
metadata:
  name: query-sample
spec:
  input: Calculate 2+2.
  targets:
    - type: agent
      name: azure
    - type: agent
      name: gemini
