apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.modelName }}-model-token
type: Opaque
stringData:
  # Make sure to use
  # export GEMINI_API_KEY="key"
  # envsubst < models/{{ .Values.modelName }}.yaml | kubectl apply -f -
  token: ${GEMINI_API_KEY}
---
apiVersion: ark.mckinsey.com/v1alpha1
kind: Model
metadata:
  name: {{ .Values.modelName }}
spec:
  type: openai
  model:
    value: gemini-2.0-flash
  config:
    openai:
      baseUrl:
        value: ${GEMINI_BASE_URL}
      apiKey:
        valueFrom:
          secretKeyRef:
            name: {{ .Values.modelName }}-model-token
            key: token
