# Create the localhost Gateway
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
  annotations:
    # Gateway for localhost development with nip.io DNS
    description: "Provides wildcard routing for service.namespace.127.0.0.1.nip.io:8080 pattern"
    ark.mckinsey.com/localhost-gateway-port: "{{ .Values.localhost.port | default "8080" }}"
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  gatewayClassName: nginx
  listeners:
  - name: http-wildcard
    port: 80
    protocol: HTTP
    hostname: "*.127.0.0.1.nip.io"  # service.ip.nip.io pattern for subdomains
    allowedRoutes:
      namespaces:
        from: All  # Allow HTTPRoutes from any namespace
  - name: http-root
    port: 80
    protocol: HTTP
    hostname: "127.0.0.1.nip.io"  # root domain pattern
    allowedRoutes:
      namespaces:
        from: All  # Allow HTTPRoutes from any namespace
