{{- if .Values.postgres.enabled }}
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{ include "postgres-memory.fullname" . }}-postgres
  labels:
    {{- include "postgres-memory.labels" . | nindent 4 }}
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-15.4-1
  postgresVersion: {{ .Values.postgres.version | default 15 }}
  
  instances:
  - name: instance1
    replicas: 1
    dataVolumeClaimSpec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: {{ .Values.postgres.storage | default "1Gi" }}

  users:
  - name: {{ .Values.postgres.username | default "postgres" }}
    databases:
    - {{ .Values.postgres.database | default "memory" }}
{{- end }}