{{- if .Values.gateway.enabled | default true }}
# HTTPRoute for explicit namespace access
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.service.name }}-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  annotations:
    description: "Routes ark-mcp with explicit namespace"
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
    namespace: {{ .Values.gateway.namespace }}
  hostnames:
  - "ark-mcp.{{ .Release.Namespace }}.127.0.0.1.nip.io"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
{{- end }}