{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccount.name }}-ark-mcp
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
  # Permission to list namespaces (cluster-scoped resource)
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  # Permission to read ark.mckinsey.com resources across all namespaces
  - apiGroups: ["ark.mckinsey.com"]
    resources: ["agents"]
    verbs: ["get", "list", "watch"]
  # Permission to create and manage queries (MCP server creates queries)
  - apiGroups: ["ark.mckinsey.com"]
    resources: ["queries"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceAccount.name }}-ark-mcp
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.serviceAccount.name }}-ark-mcp
  apiGroup: rbac.authorization.k8s.io
{{- end }}
