# HTTPRoute for explicit namespace access
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: langfuse-telemetry
  namespace: {{ .Values.namespace }}
  annotations:
    description: "Routes langfuse with explicit namespace"
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
    namespace: {{ .Values.gateway.namespace }}
  hostnames:
  - "langfuse.{{ .Values.namespace }}.127.0.0.1.nip.io"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}