# Default values for {{ .Values.projectName }}
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Project configuration
project:
  name: {{ .Values.projectName }}
  namespace: {{ .Values.namespace }}

# Image configuration
image:
  registry: localhost:5000
  tag: latest
  pullPolicy: IfNotPresent

# Model configurations
# Models are deployed from the models/ directory
# Edit files in models/ to configure your model providers

# Agent configurations
# Agents are deployed from the agents/ directory
# Edit files in agents/ to configure your agents

# Team configurations
# Teams are deployed from the teams/ directory
# Edit files in teams/ to configure your teams

# Query configurations
# Queries are deployed from the queries/ directory
# Edit files in queries/ to configure your queries

# Tools configuration
# Tools are deployed from the tools/ directory as YAML files
# Each .yaml file in tools/ is automatically deployed

# MCP Servers configuration
# MCP servers are deployed from the mcp-servers/ directory
# Use 'ark generate mcp-server <name>' to create new MCP servers

# Memory configuration
memory:
  enabled: true
  name: postgres-memory
  type: postgres
  url: "http://postgres-memory:8080"

# Security
security:
  # Pod security context
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 2000

  # Container security context
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop:
        - ALL

# Service configuration
service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: {{ .Values.projectName }}.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Resource defaults
resources:
  limits:
    memory: "1Gi"
    cpu: "1000m"
  requests:
    memory: "512Mi"
    cpu: "500m"

# Node selection
nodeSelector: {}
tolerations: []
affinity: {}

# Monitoring
monitoring:
  enabled: false
  serviceMonitor:
    enabled: false
    interval: 30s

# Logging
logging:
  level: INFO
  format: json

# Environment variables
env: {}

# Additional labels
labels: {}

# Additional annotations
annotations: {}

# Service Account configuration
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# Custom secrets (will be created)
secrets:
  {}
  # example-secret:
  #   data:
  #     key: value

# Custom config maps
configMaps:
  {}
  # example-config:
  #   data:
  #     config.yaml: |
  #       key: value
