# RoleBinding to grant the default service account access to essential 
# Kubernetes resources and ARK resources within the namespace.

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: ark
    app.kubernetes.io/managed-by: kustomize
  name: ark-tenant-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: ark-tenant-role
  apiGroup: rbac.authorization.k8s.io