apiVersion: ark.mckinsey.com/v1alpha1
kind: Query
metadata:
  name: memory-followup
spec:
  input: "What is my name? Do you remember what I told you earlier?"
  targets:
    - type: agent
      name: amazed
  sessionId: test-session-2010